In [1]:
#!pip install fuzzywuzzy

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
j15 = pd.read_csv('./data/comunio_J15.csv')
j16 = pd.read_csv('./data/comunio_J16.csv')
j17 = pd.read_csv('./data/comunio_J17.csv')
j18 = pd.read_csv('./data/comunio_J18.csv')

In [4]:
j18 = j18.drop(['Last_5_games_points'], axis=1)

In [5]:

j18['J_11'] = j15['J_11']
j18['J_12'] = j15['J_12']
j18['J_13'] = j15['J_13']

j18['Value_J_15'] = j15['Value']
j18['Value_J_16'] = j16['Value']
j18['Value_J_17'] = j17['Value']

In [6]:
'''gk = j17.loc[j17['Position']=='PT'].sort_values('Total_Points', ascending=False)[1:6]
df = j17.loc[j17['Position']=='DF'].sort_values('Total_Points', ascending=False)[0:11]
md = j17.loc[j17['Position']=='MD'].sort_values('Total_Points', ascending=False)[:15]
dl = j17.loc[j17['Position']=='DL'].sort_values('Total_Points', ascending=False)[:15]'''

gk = j18.loc[j18['Position']=='PT'].sort_values('Total_Points', ascending=False)[0:5]
df = j18.loc[j18['Position']=='DF'].sort_values('Total_Points', ascending=False)[0:10]
md = j18.loc[j18['Position']=='MD'].sort_values('Total_Points', ascending=False)[:10]
dl = j18.loc[j18['Position']=='DL'].sort_values('Total_Points', ascending=False)[:10]

In [7]:
top_players = pd.DataFrame(gk)

In [8]:
top_players = top_players.append(df)

In [9]:
top_players = top_players.append(md)
top_players = top_players.append(dl)

In [10]:
top_players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35 entries, 73 to 22
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Team_id                 35 non-null     int64
 1   Team                    35 non-null     object
 2   Player                  35 non-null     object
 3   Position                35 non-null     object
 4   Matches_Played          35 non-null     int64
 5   On_start_%              35 non-null     int64
 6   Goals_/_Goals_Received  35 non-null     int64
 7   Assists                 35 non-null     int64
 8   Total_Points            35 non-null     int64
 9   Points_Average          35 non-null     float64
 10  J_14                    35 non-null     int64
 11  J_15                    35 non-null     int64
 12  J_16                    35 non-null     int64
 13  J_17                    35 non-null     int64
 14  J_18                    35 non-null     int64
 15  Avg_last_5_games        35 non-null     float64
 16  Value                   35 non-null     int64
 17  J_11                    35 non-null     float64
 18  J_12                    35 non-null     float64
 19  J_13                    35 non-null     float64
 20  Value_J_15              35 non-null     float64
 21  Value_J_16              35 non-null     float64
 22  Value_J_17              35 non-null     float64
dtypes: float64(8), int64(12), object(3)
memory usage: 6.6+ KB

In [11]:
top_players.columns

Index(['Team_id', 'Team', 'Player', 'Position', 'Matches_Played', 'On_start_%',
       'Goals_/_Goals_Received', 'Assists', 'Total_Points', 'Points_Average',
       'J_14', 'J_15', 'J_16', 'J_17', 'J_18', 'Avg_last_5_games', 'Value',
       'J_11', 'J_12', 'J_13', 'Value_J_15', 'Value_J_16', 'Value_J_17'],
      dtype='object')

In [12]:
new_columns = ['Team_id', 'Team', 'Player', 'Position', 'Matches_Played', 'On_start_%',
       'Goals_/_Goals_Received', 'Assists', 'Total_Points', 'Points_Average',
       'J_11', 'J_12','J_13', 'J_14', 'J_15', 'J_16', 'J_17','J_18', 'Avg_last_5_games',
        'Value_J_15', 'Value_J_16' ,'Value_J_17','Value']

In [13]:
top_players = top_players.reindex(columns=new_columns)
top_players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35 entries, 73 to 22
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Team_id                 35 non-null     int64
 1   Team                    35 non-null     object
 2   Player                  35 non-null     object
 3   Position                35 non-null     object
 4   Matches_Played          35 non-null     int64
 5   On_start_%              35 non-null     int64
 6   Goals_/_Goals_Received  35 non-null     int64
 7   Assists                 35 non-null     int64
 8   Total_Points            35 non-null     int64
 9   Points_Average          35 non-null     float64
 10  J_11                    35 non-null     float64
 11  J_12                    35 non-null     float64
 12  J_13                    35 non-null     float64
 13  J_14                    35 non-null     int64
 14  J_15                    35 non-null     int64
 15  J_16                    35 non-null     int64
 16  J_17                    35 non-null     int64
 17  J_18                    35 non-null     int64
 18  Avg_last_5_games        35 non-null     float64
 19  Value_J_15              35 non-null     float64
 20  Value_J_16              35 non-null     float64
 21  Value_J_17              35 non-null     float64
 22  Value                   35 non-null     int64
dtypes: float64(8), int64(12), object(3)
memory usage: 6.6+ KB

In [14]:
top_players.J_11 = top_players.J_11.astype(int)
top_players.J_12 = top_players.J_12.astype(int)
top_players.J_13 = top_players.J_13.astype(int)
top_players.Value_J_15 = top_players.Value_J_15.astype(int)
top_players.Value_J_16 = top_players.Value_J_16.astype(int)
top_players.Value_J_17 = top_players.Value_J_17.astype(int)

In [15]:
#top_players = top_players.loc[top_players['Matches_Played']!=0]

In [16]:
top_players = top_players.rename(columns ={'J_11':'2021-10-26', 'J_12':'2021-10-30', 'J_13':'2021-11-05', 'J_14':'2021-11-19', 
                                  'J_15': '2021-11-26', 'J_16':'2021-12-03', 'J_17':'2021-12-10','J_18':'2021-12-17', 'Value_J_15': '2021-11-26(V)', 
                                           'Value_J_16':'2021-12-03(V)', 'Value_J_17':'2021-12-10(V)', 'Value':'2021-12-17(V)'})

In [17]:
top_players['Price_per_Total_Points'] = top_players['2021-12-17(V)']/top_players.Total_Points

In [18]:
ppp = []
for value in top_players.Price_per_Total_Points:

    value = '{0:.2f}'.format(value)
    
    ppp.append(value)

In [19]:
top_players.Price_per_Total_Points = ppp

In [20]:
Price_per_Points_Last_5_J = top_players['2021-12-17(V)']/ (top_players['2021-12-17']+top_players['2021-12-10']+ top_players['2021-12-03']+top_players['2021-11-26']+top_players['2021-11-19'])

pppl5j = []

for value in Price_per_Points_Last_5_J:
    value = '{0:.2f}'.format(value)
    pppl5j.append(value)

top_players['Price_per_Point_Last_5_J']= pppl5j

In [21]:
top_players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35 entries, 73 to 22
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Team_id                   35 non-null     int64
 1   Team                      35 non-null     object
 2   Player                    35 non-null     object
 3   Position                  35 non-null     object
 4   Matches_Played            35 non-null     int64
 5   On_start_%                35 non-null     int64
 6   Goals_/_Goals_Received    35 non-null     int64
 7   Assists                   35 non-null     int64
 8   Total_Points              35 non-null     int64
 9   Points_Average            35 non-null     float64
 10  2021-10-26                35 non-null     int32
 11  2021-10-30                35 non-null     int32
 12  2021-11-05                35 non-null     int32
 13  2021-11-19                35 non-null     int64
 14  2021-11-26                35 non-null     int64
 15  2021-12-03                35 non-null     int64
 16  2021-12-10                35 non-null     int64
 17  2021-12-17                35 non-null     int64
 18  Avg_last_5_games          35 non-null     float64
 19  2021-11-26(V)             35 non-null     int32
 20  2021-12-03(V)             35 non-null     int32
 21  2021-12-10(V)             35 non-null     int32
 22  2021-12-17(V)             35 non-null     int64
 23  Price_per_Total_Points    35 non-null     object
 24  Price_per_Point_Last_5_J  35 non-null     object
dtypes: float64(2), int32(6), int64(12), object(5)
memory usage: 6.3+ KB

In [22]:
top_players

,Team_id,Team,Player,Position,Matches_Played,On_start_%,Goals_/_Goals_Received,Assists,Total_Points,Points_Average,2021-10-26,2021-10-30,2021-11-05,2021-11-19,2021-11-26,2021-12-03,2021-12-10,2021-12-17,Avg_last_5_games,2021-11-26(V),2021-12-03(V),2021-12-10(V),2021-12-17(V),Price_per_Total_Points,Price_per_Point_Last_5_J
73,4,RCD Espanyol de Barcelona,Diego López,PT,18,100,19,0,105,5.8,0,0,0,7,11,2,1,0,4.2,290000,4420000,4260000,4260000,40571.43,202857.14
203,9,Rayo Vallecano de Madrid,Dimitrievski,PT,0,94,0,0,101,5.6,4,8,3,4,4,8,4,11,6.2,2530000,180000,470000,3650000,36138.61,117741.94
176,8,Real Madrid CF,Courtois,PT,18,100,15,0,89,4.9,0,0,0,3,5,5,12,5,6.0,3220000,410000,10490000,6740000,75730.34,224666.67
338,14,Villarreal CF,Rulli,PT,15,88,13,0,86,5.7,0,0,0,0,0,4,12,4,4.0,4160000,6230000,4800000,4150000,48255.81,207500.00
487,20,Sevilla FC,Bono,PT,15,88,9,1,82,5.5,0,0,0,1,-1,7,8,3,3.6,990000,6340000,4070000,5020000,61219.51,278888.89
179,8,Real Madrid CF,Éder Militão,DF,17,94,0,1,101,5.9,0,0,0,0,9,10,6,7,6.4,1210000,3160000,6420000,7910000,78316.83,247187.50
178,8,Real Madrid CF,Alaba,DF,0,94,0,0,101,5.9,6,3,4,3,8,5,4,6,5.2,5580000,7620000,2750000,10330000,102277.23,397307.69
49,3,CA Osasuna,David García Zub.,DF,17,94,3,0,101,5.9,7,3,6,6,4,7,9,0,5.2,4970000,5170000,5200000,4890000,48415.84,188076.92
489,20,Sevilla FC,Diego Carlos,DF,16,94,2,0,92,5.8,6,5,7,3,1,8,6,5,4.6,7530000,1040000,910000,7180000,78043.48,312173.91
312,13,Real Sociedad de Fútbol,Le Normand,DF,18,100,0,1,90,5.0,2,4,2,9,4,3,2,6,4.8,1720000,2820000,870000,4960000,55111.11,206666.67
206,9,Rayo Vallecano de Madrid,Catena,DF,18,100,1,1,88,4.9,0,5,0,4,4,6,2,12,5.6,330000,2700000,1590000,3230000,36704.55,115357.14
126,6,Getafe CF,Damián Suárez,DF,16,78,0,3,86,5.4,0,0,2,11,7,0,6,7,6.2,1710000,1640000,2260000,3960000,46046.51,127741.94
283,2,Real Betis Balompié,Álex Moreno,DF,0,78,0,0,84,5.6,0,0,0,7,5,8,23,0,8.6,1920000,1570000,2370000,4750000,56547.62,110465.12
313,13,Real Sociedad de Fútbol,Aritz Elustondo,DF,0,78,0,0,84,5.3,0,0,0,-4,0,0,0,2,-0.4,360000,940000,1300000,5800000,69047.62,-2900000.00
258,11,RCD Mallorca,Maffeo,DF,16,89,1,0,80,5.0,0,-3,0,4,2,2,4,2,2.8,390000,1650000,2040000,5210000,65125.00,372142.86
13,1,Athletic Club,Muniain,MD,17,94,2,5,115,6.8,4,14,6,4,9,0,0,7,4.0,9240000,9650000,10280000,9940000,86434.78,497000.00
292,2,Real Betis Balompié,Fekir,MD,0,89,0,0,110,6.9,0,0,2,12,7,0,12,10,8.2,2800000,11380000,3110000,11480000,104363.64,280000.00
187,8,Real Madrid CF,Casemiro,MD,17,89,0,3,108,6.4,2,4,2,11,5,9,8,9,8.4,4110000,16160000,10310000,12630000,116944.44,300714.29
213,9,Rayo Vallecano de Madrid,Álvaro García,MD,18,94,5,2,106,5.9,4,2,3,10,3,7,6,7,6.6,5750000,8840000,5290000,10200000,96226.42,309090.91
214,9,Rayo Vallecano de Madrid,Trejo,MD,16,83,3,8,101,6.3,3,2,0,14,0,2,3,5,4.8,3280000,5490000,3700000,9880000,97821.78,411666.67
379,15,Valencia CF,Carlos Soler,MD,14,67,7,2,99,7.1,0,0,2,5,9,2,10,17,8.6,360000,1540000,1260000,12320000,124444.44,286511.63
108,5,FC Barcelona,Sergio Busquets,MD,0,100,0,0,95,5.6,-2,4,0,7,4,9,5,2,5.4,3680000,13530000,12790000,9340000,98315.79,345925.93
350,14,Villarreal CF,Parejo,MD,14,76,0,4,93,6.6,2,1,8,10,7,5,7,8,7.4,5690000,4200000,6840000,13890000,149354.84,375405.41
188,8,Real Madrid CF,Kroos,MD,11,61,1,2,92,8.4,0,0,0,13,7,5,6,11,8.4,1830000,10540000,6050000,17100000,185869.57,407142.86
472,19,RC Celta de Vigo,Denis Suárez,MD,18,78,2,1,91,5.1,0,3,0,5,2,5,2,15,5.8,470000,3110000,680000,6180000,67912.09,213103.45
195,8,Real Madrid CF,Benzema,DL,0,94,0,0,173,10.2,2,2,0,7,10,2,9,7,7.0,3200000,18040000,7650000,23910000,138208.09,683142.86
196,8,Real Madrid CF,Vinícius Júnior,DL,18,89,10,4,150,8.3,0,0,0,12,9,13,10,4,9.6,4660000,6710000,5350000,19980000,133200.00,416250.00
114,5,FC Barcelona,Depay,DL,15,88,8,2,130,8.7,2,0,0,12,8,4,0,0,4.8,3150000,16120000,15420000,18150000,139615.38,756250.00
483,19,RC Celta de Vigo,Iago Aspas,DL,17,89,8,2,125,7.4,1,14,6,5,9,8,0,15,7.4,4370000,5030000,800000,18960000,151680.00,512432.43
307,2,Real Betis Balompié,Juanmi Jiménez,DL,0,67,0,0,123,7.7,15,5,6,11,21,11,9,9,12.2,6210000,5780000,3880000,9970000,81056.91,163442.62
387,15,Valencia CF,Guedes,DL,0,94,0,0,123,6.8,9,6,3,2,3,2,11,19,7.4,3800000,890000,2890000,10940000,88943.09,295675.68
411,16,Deportivo Alavés,Joselu,DL,17,88,8,1,114,6.7,2,0,5,9,11,5,9,3,7.4,1570000,2630000,230000,12910000,113245.61,348918.92
95,4,RCD Espanyol de Barcelona,Raúl de Tomás,DL,17,94,8,2,113,6.6,2,2,2,6,5,5,12,2,6.0,1770000,890000,870000,18470000,163451.33,615666.67
484,19,RC Celta de Vigo,Santi Mina,DL,17,94,6,3,102,6.0,1,2,16,3,7,3,3,12,5.6,7440000,850000,6900000,9520000,93333.33,340000.00
22,1,Athletic Club,Williams,DL,0,89,0,0,97,5.4,13,4,3,2,2,4,4,16,5.6,9680000,9220000,9020000,9000000,92783.51,321428.57

In [24]:
top_players.to_excel('data/comunio_tableau_J18.xlsx', sheet_name='top_players')