In [1]:
from modelos import comunio_pred_lib
import pandas as pd

In [2]:
data = comunio_pred_lib.create_df(31)

In [3]:
pred = round(pd.DataFrame(comunio_pred_lib.predict_rf(data)))
pred_xgb = round(pd.DataFrame(comunio_pred_lib.predict_xgb(data)))
pred_gb = round(pd.DataFrame(comunio_pred_lib.predict_gb(data)))

RF MSE en test 2.9006398077071425
XGB MSE en test 2.795236256472498
GB MSE en test 2.935559585345974

In [4]:
data['pred'] = pred

In [5]:
data['pred_xgb'] = pred_xgb
data['pred_gb'] = pred_gb
data

,Team,Player,Position,Total_Points,Points_Average,Value,On_start_%,Last_5_games_points,J_27,J_28,...,Vs_Squad_Points_J_28,Vs_Squad_Points_J_29,Vs_Squad_Points_J_30,Vs_Squad_Points_J_31,Vs_Squad_Avg_last_5_Games,Team_clas,Vs_Team_clas,pred,pred_xgb,pred_gb
0,Athletic Club,Unai Simón,PT,122,4.5,3560000,87,"['2', '5', '2', '2', '5']",2,5,...,42,64,62,44,52.6,8,12,4.0,5.0,4.0
1,Athletic Club,Agirrezabala,PT,20,5.0,390000,13,"['-', '-', '-', '-', '-']",0,0,...,42,64,62,44,52.6,8,12,0.0,1.0,1.0
2,Athletic Club,Ezkieta,PT,0,0.0,180000,0,"['-', '-', '-', '-', '-']",0,0,...,42,64,62,44,52.6,8,12,0.0,0.0,1.0
3,Athletic Club,Iñigo Martínez,DF,115,5.5,5560000,65,"['7', '-', '-', '-', '-']",7,0,...,42,64,62,44,52.6,8,12,3.0,3.0,4.0
4,Athletic Club,Daniel Vivian,DF,103,5.4,3390000,58,"['2', '4', '6', '2', '3']",2,4,...,42,64,62,44,52.6,8,12,4.0,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,Sevilla,Munir El Haddadi,DL,54,3.4,1220000,13,"['2', '2', '2', '-', '-']",2,2,...,88,34,70,100,77.6,3,1,2.0,2.0,2.0
571,Sevilla,Jesús Corona,DL,41,3.7,7850000,23,"['4', '6', '2', '2', '8']",4,6,...,88,34,70,100,77.6,3,1,4.0,2.0,3.0
572,Sevilla,Suso,DL,27,3.4,920000,19,"['-', '-', '-', '-', '-']",0,0,...,88,34,70,100,77.6,3,1,0.0,0.0,1.0
573,Sevilla,Martial,DL,16,2.3,9900000,19,"['-', '2', '2', '1', '1']",0,2,...,88,34,70,100,77.6,3,1,2.0,2.0,2.0
574,Sevilla,Iván Romero,DL,5,1.7,290000,6,"['-', '-', '-', '-', '-']",0,0,...,88,34,70,100,77.6,3,1,0.0,0.0,1.0

In [6]:
preds_31 = data[['Player','Position', 'pred', 'pred_xgb', 'pred_gb']]

In [7]:
preds_31

               Player Position  pred  pred_xgb  pred_gb
0          Unai Simón       PT   4.0       5.0      4.0
1        Agirrezabala       PT   0.0       1.0      1.0
2             Ezkieta       PT   0.0       0.0      1.0
3      Iñigo Martínez       DF   3.0       3.0      4.0
4       Daniel Vivian       DF   4.0       4.0      3.0
..                ...      ...   ...       ...      ...
570  Munir El Haddadi       DL   2.0       2.0      2.0
571      Jesús Corona       DL   4.0       2.0      3.0
572              Suso       DL   0.0       0.0      1.0
573           Martial       DL   2.0       2.0      2.0
574       Iván Romero       DL   0.0       0.0      1.0

[575 rows x 5 columns]

In [8]:
data_32 = comunio_pred_lib.create_df(32)

In [9]:
real = data_32[['Player', 'J_32']]
preds_31 = preds_31.merge(real, left_on='Player',right_on='Player')

In [10]:
preds_31

               Player Position  pred  pred_xgb  pred_gb  J_32
0          Unai Simón       PT   4.0       5.0      4.0     1
1        Agirrezabala       PT   0.0       1.0      1.0     0
2             Ezkieta       PT   0.0       0.0      1.0     0
3      Iñigo Martínez       DF   3.0       3.0      4.0     0
4       Daniel Vivian       DF   4.0       4.0      3.0     4
..                ...      ...   ...       ...      ...   ...
570  Munir El Haddadi       DL   2.0       2.0      2.0     0
571      Jesús Corona       DL   4.0       2.0      3.0     5
572              Suso       DL   0.0       0.0      1.0     0
573           Martial       DL   2.0       2.0      2.0     2
574       Iván Romero       DL   0.0       0.0      1.0     0

[575 rows x 6 columns]

In [11]:
dif = preds_31.J_32 == preds_31.pred_xgb
dif.value_counts()

False    385
True     190
dtype: int64

In [12]:
dif = preds_31.J_32 == preds_31.pred_gb
dif.value_counts()

False    522
True      53
dtype: int64

In [13]:
dif = preds_31.J_32 == preds_31.pred
dif.value_counts()

False    399
True     176
dtype: int64

In [14]:
squad = ['Courtois', 'Bono',
         'Balliu', 'Fran García',
         #'Ronald Araujo', 
         'Alderete', 'Manu Sánchez', 
         #'Giménez',
         'Yéremi',  'Gavi',  'Modric',  'Brais', 'Papu Gómez', 'Dani Rodríguez', 'Pere Milla', 'Cervi', 'Berenguer',
         'Vinícius Júnior', 'Aubameyang', 'Sancet', 'João Félix', 'Morales']
df_squad_kike = pd.DataFrame()
for player in squad:
    #print (player)
    for p in preds_31.Player:
        if player in p:
            #print('encontrado')
            add_player = pd.DataFrame(preds_31.loc[preds_31.Player==p])
            #print(add_player)
            df_squad_kike = df_squad_kike.append(add_player)
print(len(squad),len(df_squad_kike))

df_squad_kike.at[514,'Position'] = 'MD'
round(df_squad_kike)

20 20

              Player Position  pred  pred_xgb  pred_gb  J_32
199         Courtois       PT   5.0       4.0      3.0     0
545             Bono       PT   3.0       2.0      3.0     0
233           Balliu       DF   4.0       6.0      5.0    -4
234      Fran García       DF   4.0       3.0      4.0     4
410    Omar Alderete       DF   4.0       4.0      3.0     0
53      Manu Sánchez       DF   3.0       2.0      3.0     2
393      Yéremi Pino       MD   4.0       4.0      3.0     2
120             Gavi       MD   4.0       4.0      3.0     5
213           Modric       MD   3.0       2.0      2.0     3
528     Brais Méndez       MD   4.0       3.0      3.0     8
558       Papu Gómez       MD   4.0       3.0      3.0     2
297   Dani Rodríguez       MD   4.0       5.0      4.0     2
514       Pere Milla       MD   3.0       4.0      3.0     2
530     Franco Cervi       MD   3.0       4.0      3.0     5
14    Álex Berenguer       MD   5.0       3.0      3.0     4
221  Vinícius Júnior       DL   5.0       4.0      3.0     1
129       Aubameyang       DL   6.0       4.0      4.0     1
22            Sancet       DL   4.0       4.0      3.0     2
46        João Félix       DL   5.0       7.0      3.0     1
280          Morales       DL   4.0       3.0      3.0    16

### Previsiones para la Jornada 33

In [15]:
data_32 = comunio_pred_lib.create_df(32)
pred_rfr = round(pd.DataFrame(comunio_pred_lib.predict_rf(data_32)))
pred_xgb = round(pd.DataFrame(comunio_pred_lib.predict_xgb(data_32)))
pred_gb = round(pd.DataFrame(comunio_pred_lib.predict_gb(data_32)))
data_32['rfr'] = pred_rfr
data_32['xgb'] = pred_xgb
data_32['gb'] = pred_gb

preds = data_32[['Player','Position', 'rfr', 'xgb', 'gb']]

RF MSE en test 2.8899972771114366
XGB MSE en test 2.795236256472498
GB MSE en test 2.9329932992138654

In [16]:
squad = ['Courtois', 'Bono',
         #'Balliu', 
         'Fran García','Ronald Araujo', 'Alderete', 'Manu Sánchez', 
         #'Giménez',
         'Yéremi',  'Gavi',  
         #'Modric',  
         'Brais', 'Papu Gómez', 'Dani Rodríguez', 'Pere Milla', 'Cervi', 'Berenguer',
         'Vinícius Júnior', 'Aubameyang', 'Sancet', 
         #'João Félix', 
         'Morales']
df_squad_kike = pd.DataFrame()
for player in squad:
    #print (player)
    for p in preds.Player:
        if player in p:
            #print('encontrado')
            add_player = pd.DataFrame(preds.loc[preds.Player==p])
            #print(add_player)
            df_squad_kike = df_squad_kike.append(add_player)
print(len(squad),len(df_squad_kike))

df_squad_kike.at[514,'Position'] = 'MD'
round(df_squad_kike)

18 18

              Player Position  rfr  xgb   gb
199         Courtois       PT  5.0  6.0  4.0
545             Bono       PT  5.0  4.0  4.0
233      Fran García       DF  3.0  1.0  3.0
109    Ronald Araujo       DF  5.0  9.0  4.0
410    Omar Alderete       DF  3.0  2.0  3.0
53      Manu Sánchez       DF  3.0  2.0  3.0
394      Yéremi Pino       MD  4.0  4.0  3.0
120             Gavi       MD  4.0  5.0  3.0
528     Brais Méndez       MD  5.0  4.0  4.0
558       Papu Gómez       MD  4.0  4.0  4.0
297   Dani Rodríguez       MD  4.0  4.0  4.0
514       Pere Milla       MD  3.0  3.0  2.0
530     Franco Cervi       MD  5.0  6.0  3.0
14    Álex Berenguer       MD  4.0  4.0  3.0
221  Vinícius Júnior       DL  5.0  7.0  5.0
129       Aubameyang       DL  5.0  7.0  4.0
23            Sancet       DL  3.0  3.0  3.0
280          Morales       DL  5.0  6.0  3.0

In [17]:
def once_ideal_xbgr(data):
    gk = data.loc[data['Position']=='PT'].sort_values('xgb', ascending=False)[:1]
    df = data.loc[data['Position']=='DF'].sort_values('xgb', ascending=False)[:3]
    md = data.loc[data['Position']=='MD'].sort_values('xgb', ascending=False)[:4]
    dl = data.loc[data['Position']=='DL'].sort_values('xgb', ascending=False)[:3]
    positions = [gk, df, md, dl]
    squad = pd.DataFrame()
    for pos in positions:
        squad = squad.append(pd.DataFrame(pos))
    
    return squad

def once_ideal_rf(data):
    gk = data.loc[data['Position']=='PT'].sort_values('rfr', ascending=False)[:1]
    df = data.loc[data['Position']=='DF'].sort_values('rfr', ascending=False)[:3]
    md = data.loc[data['Position']=='MD'].sort_values('rfr', ascending=False)[:4]
    dl = data.loc[data['Position']=='DL'].sort_values('rfr', ascending=False)[:3]
    positions = [gk, df, md, dl]
    squad = pd.DataFrame()
    for pos in positions:
        squad = squad.append(pd.DataFrame(pos))
    
    return squad

def once_ideal_gb(data):
    gk = data.loc[data['Position']=='PT'].sort_values('gb', ascending=False)[:1]
    df = data.loc[data['Position']=='DF'].sort_values('gb', ascending=False)[:3]
    md = data.loc[data['Position']=='MD'].sort_values('gb', ascending=False)[:4]
    dl = data.loc[data['Position']=='DL'].sort_values('gb', ascending=False)[:3]
    positions = [gk, df, md, dl]
    squad = pd.DataFrame()
    for pos in positions:
        squad = squad.append(pd.DataFrame(pos))
    
    return squad

In [18]:
xgb_eleven = round(once_ideal_xbgr(df_squad_kike))
rf_eleven = round(once_ideal_rf(df_squad_kike))
gb_eleven = round(once_ideal_gb(df_squad_kike))

In [19]:
xgb_eleven

              Player Position  rfr  xgb   gb
199         Courtois       PT  5.0  6.0  4.0
109    Ronald Araujo       DF  5.0  9.0  4.0
410    Omar Alderete       DF  3.0  2.0  3.0
53      Manu Sánchez       DF  3.0  2.0  3.0
530     Franco Cervi       MD  5.0  6.0  3.0
120             Gavi       MD  4.0  5.0  3.0
394      Yéremi Pino       MD  4.0  4.0  3.0
528     Brais Méndez       MD  5.0  4.0  4.0
221  Vinícius Júnior       DL  5.0  7.0  5.0
129       Aubameyang       DL  5.0  7.0  4.0
280          Morales       DL  5.0  6.0  3.0

In [20]:
rf_eleven

              Player Position  rfr  xgb   gb
199         Courtois       PT  5.0  6.0  4.0
109    Ronald Araujo       DF  5.0  9.0  4.0
233      Fran García       DF  3.0  1.0  3.0
410    Omar Alderete       DF  3.0  2.0  3.0
528     Brais Méndez       MD  5.0  4.0  4.0
530     Franco Cervi       MD  5.0  6.0  3.0
394      Yéremi Pino       MD  4.0  4.0  3.0
120             Gavi       MD  4.0  5.0  3.0
221  Vinícius Júnior       DL  5.0  7.0  5.0
129       Aubameyang       DL  5.0  7.0  4.0
280          Morales       DL  5.0  6.0  3.0

In [21]:
gb_eleven

              Player Position  rfr  xgb   gb
199         Courtois       PT  5.0  6.0  4.0
109    Ronald Araujo       DF  5.0  9.0  4.0
233      Fran García       DF  3.0  1.0  3.0
410    Omar Alderete       DF  3.0  2.0  3.0
528     Brais Méndez       MD  5.0  4.0  4.0
558       Papu Gómez       MD  4.0  4.0  4.0
297   Dani Rodríguez       MD  4.0  4.0  4.0
394      Yéremi Pino       MD  4.0  4.0  3.0
221  Vinícius Júnior       DL  5.0  7.0  5.0
129       Aubameyang       DL  5.0  7.0  4.0
23            Sancet       DL  3.0  3.0  3.0

In [22]:
print('Totales xgb: ', sum(xgb_eleven.xgb), ', real: ', 
      #sum(xgb_eleven.J_32)
     )
print('Totales rfr: ', sum(rf_eleven.rfr), ', real: ', 
      #sum(rf_eleven.J_32)
     )
print('Totales gb: ', sum(gb_eleven.gb), ', real: ', 
      #sum(gb_eleven.J_32)
     )

Totales xgb:  58.0 , real:
Totales rfr:  49.0 , real:
Totales gb:  41.0 , real:

In [3]:
pred_rfr = round(pd.DataFrame(comunio_pred_lib.predict_rf(data)))
pred_xgb = round(pd.DataFrame(comunio_pred_lib.predict_xgb(data)))
pred_gb = round(pd.DataFrame(comunio_pred_lib.predict_gb(data)))

In [5]:
pred_xgb

       0
0    5.0
1    1.0
2    0.0
3    3.0
4    4.0
..   ...
570  2.0
571  2.0
572  0.0
573  2.0
574  0.0

[575 rows x 1 columns]